import type { Metadata } from "next";
import "./../styles/globals.css";
import Header from "../components/ui/home/Header";
import Footer from "../components/ui/home/Footer";
import { FilterProvider } from "../context/FilterContext";

export const metadata: Metadata = {
  title: "آگهی ها",
  description: "Generated by create next app",
};
export default function SelectCityLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        <Header />
        {children}

        <Footer />
    </>
  );
}
