import type { Metadata } from "next";
import "@/app/styles/globals.css";
import HeaderAds from "@/app/components/ui/home/HeaderAds";
import FooterAds from "@/app/components/ui/home/FooterAds";

export const metadata: Metadata = {
  title: "آگهی",
  description: "Generated by create next app",
};
export default function AdsLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      {/* <HeaderAds /> */}

      {children}

      <FooterAds />
    </>
  );
}
