import type { Metadata } from "next";
import "./../styles/globals.css";
import MainHeader from "../components/ui/home/MainHeader";
import { FilterProvider } from "../context/FilterContext";

export const metadata: Metadata = {
  title: "آگهی ها",
  description: "Generated by create next app",
};
export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        <MainHeader />
        {children}
    </>
  );
}
